global:
  scrape_interval: 15s # Intervalo de coleta de métricas
  evaluation_interval: 15s # Intervalo de avaliação de regras

# Configuração de alertas (opcional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Regras de alertas (opcional)
rule_files:
  # - "alerts.yml"

# Configuração de scrape (coleta de métricas)
scrape_configs:
  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas da aplicação Spring Boot
  - job_name: 'agenda-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'agenda'
          environment: 'local'